### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by boardfish** [Hello1024/santander-api#3]
This seems like a perfect companion to my personal project [bank](http://github.com/boardfish/bank), but that can't happen while it's on Python 2. I remember trying to use 2to3 but there were a couple of dependencies that were tough to resolve due to changes.

**Comment by Hello1024** [comment]
Pull requests welcome, but it's unlikely I'll return to this project anytime soon.

**Comment by aCampello** [comment]
The mechanize module doesn't seem to be supported by Python 3. I suppose many parts of the code will have to be re-written in order to accommodate Selenium or MechanicalSoup...

**Comment by boardfish** [comment]
Closing, stale.
